package:
  name: jdk17
  version: 17
  epoch: 0
  description: "Adoptium Java JDK"
  target-architecture:
    - x86_64
  copyright:
    - paths:
      - "*"
      attestation: |
      license: GPL-2.0-classpath-exception
  dependencies:
    runtime:
      - musl-dev
      - zlib

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox
      - ca-certificates-bundle
      - musl-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4%2B8/OpenJDK17U-jdk_x64_alpine-linux_hotspot_17.0.4_8.tar.gz
      expected-sha256: 3b356512c955f2d1a66b714ab3acaad942d04f80603af7dcd56e1fe5baeaeeda
  - name: 'Copy paths'
    runs: |
      cp --parents -r * ${{targets.destdir}}/usr/
